### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by AwesomeLemon** [austinxu87/handsoff#1]
Hi,
Your paper is very interesting. I was wondering when approximately will the source code be made available?

**Comment by Seungeun-Han** [comment]
i was wondering too :)
i hope your source code be made available ASAP. 😊

**Comment by austinxu87** [comment]
Thanks for your interest, the initial code release is live now. In the upcoming weeks, I'm aiming to release some of our pretrained models, GAN inversion latents, and dataset splits
